import './styles/globals.css'
import Navbar from './components/Navbar'
import Footer from './components/Footer';
import { Inter } from 'next/font/google'

import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import CopyRight from './components/CopyRight';
config.autoAddCss = false;

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'XdataLogix',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
        <CopyRight />
      </body>
    </html>
  )
}
